config/routes.rb
Stanceshare2::Application.routes.draw do
  resources :parts

  devise_for :users
  get 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'
  post 'users' => 'users#create'

  root :to => 'parts#index'

  

end

app/models/part.rb
class Part < ActiveRecord::Base
  attr_accessor :image_remote_url
  attr_accessible :image, :image_remote_url, :description

  validates :description, presence: true
  validates :user_id, presence: true
  
  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}
  validates_attachment :image, presence: true,
  	content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
	size: { less_than: 5.megabytes }

	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super
	end
end 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :recoverable, 
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :parts, :dependent => :destroy
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end
		

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  # GET /parts
  # GET /parts.json
  def index
    # @parts = part.all
    @parts = Part.order('created_at desc').page(params[:page]).per_page(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parts }
    end
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/new
  # GET /parts/new.json
  def new
    @part = current_user.parts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/1/edit
  def edit
    @part = current_user.parts.find(params[:id])
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = current_user.parts.new(params[:part])

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Car part was successfully posted!' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parts/1
  # PUT /parts/1.json
  def update
    @part = current_user.parts.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to @part, notice: 'part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part = current_user.parts.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@parts = @user.parts.page(params[:page]).per_page(10)
	end

	def create
		@user = User.new(params[:user].permit(:name, :email))
		@user.save 
		redirect_to 'index'
	end

	def index
		@user = User.all
		render nothing: true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
	<div class='footer'>
			<p>
				<%= link_to 'StanceTrader', 'https://stancetrader.com' %> by <%= link_to 'raysspl', 'http://github.com/raysspl' %>
			</p>
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to 'StanceShare', root_path, class: 'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class='nav'>
	        <li><%= link_to 'Home', root_path %></li>
					<li><%= link_to 'About', about_path %></li>
				</ul>
				<ul class='nav pull-right'>
          <% if user_signed_in? %>
         
          <li><%= link_to 'Profile', edit_user_registration_path %></li>
					<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
				</ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
	  <title>StanceShare</title>
	  <%= stylesheet_link_tag "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		
		<div class='container'>
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: 'alert alert-#{name') %>
				<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
		
	</body>
</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %> 

	<div class="hero-unit">
			<h1>Welcome to StanceShare!</h1>
			<h2>Connect. Share. Discover.</h2>

			<h4>
				share your passion and connect with gearheads who have many car parts to share.
			</h4>
			<h4>
				Discover new car parts you never thought of using, pin them, and discuss with fellow gearheads who share the same passion as you.
			</h4>
			<p>
					<%= link_to 'Sign Up Now!', new_user_registration_path, class: 'btn btn-primary btn-large' %>
			</p>
			<p>
				I'm also currently working on an enthusiast marketplace for hot-rodders and gearheads called <%= link_to 'StanceTrader', 'https://stancetrader.com' %>
			</p>
	</div>
<% end %>

app/views/pages/about.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>

<h1>About</h1>
	<p>Hey there!</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
    <h1>Welcome to <%= link_to 'StanceShare', 'http://github.com/raysspl' %>
    </h1>

    <p> <%= link_to 'Sign up now!',  new_user_registration_path, class: "btn btn-large btn-primary" %> </p>
</div>

app/views/parts/_form.html.erb
<%= simple_form_for(@part, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload your car part!" %>
  <%= f.input :image_remote_url, label: "or enter a URL" %>
  <%= f.input :description, as: :text, input_html: { rows: "5" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<div class="box">
    <%= link_to (image_tag part.image(:medium)), part %>
    <p class="description">
        <%= part.description %>
    </p>
    <p>
        <strong>
            By <%= link_to part.user.name, part.user %>
        </strong>
    </p>
    <% if current_user == part.user %>
        <p>
          <%= link_to 'Edit', edit_part_path(part) %>
          <%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
</div>

app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<%= render 'pages/home' %>

<div id='parts'>
  <%= render partial: 'part', collection: @parts %>
</div>

<%= will_paginate @parts %>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<div class="row">
    <div class="span6 offset4">
        <div class="well">
            <%= image_tag @part.image %>
            <p>
              <%= @part.description %>
            </p>
            <p>
              <%= @part.user.name %>
            </p>
            <% if current_user == @part.user %>
                <%= link_to 'Edit', edit_part_path(@part) %> |
            <% end %>
            <%= link_to 'Back', parts_path %>
        </div>
    </div>
</div> 